pull_request_title: 'Lang: Updated Language Files.'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /metadata/en-US/*.txt
    translation: /metadata/%locale%/%original_file_name%