name: Bug report
description: Create a bug report
labels: [ "Type: Bug Report" ]
title: "[Bug Report] add text here"
assignees: [ "CreativeCodeCat" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping we to make MultiLauncher better by reporting a bug. :hugs:
        Please fill in as much information as possible about your bug so that we can fix it faster.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Bug Report Checklist"
      options:
        - label: "I have written the bug report in English with a clear, descriptive title."
          required: true
        - label: "I confirmed there are **no existing bug reports** — [open](https://github.com/DroidWorksStudio/yam_launcher/issues) or [closed](https://github.com/DroidWorksStudio/yam_launcher/issues?q=is%3Aissue+is%3Aclosed) — that already cover this issue."
          required: true
        - label: "I reviewed the [Known Issues](https://github.com/DroidWorksStudio/yam_launcher/blob/main/KnownIssues.md) and this bug is not listed."
          required: true
        - label: "I checked the [CHANGELOG](https://github.com/DroidWorksStudio/yam_launcher/blob/main/CHANGELOG.md) to ensure the bug hasn’t already been fixed."
          required: true
        - label: "I reproduced the bug on the **latest GitHub release**."
          required: true
        - label: "I included clear reproduction steps, expected vs. actual behavior, and any relevant logs or screenshots."
          required: true
        - label: "This submission describes **one** bug only."
          required: true
        - label: "I understand that incomplete or vague reports may be closed without investigation."
          required: true
        - label: "I optionally [donated](https://www.buymeacoffee.com/CreativeCodeCat) to support the MultiLauncher mission."
          required: false

  - type: input
    id: app-version
    attributes:
      label: App version
      description: "In which version did you encounter the bug?"
      placeholder: "xx.xx - Can be seen in the app from the 'Settings' section"
    validations:
      required: true

  - type: input
    id: device-os-info
    attributes:
      label: Android version
      description: |
        With what operating system (+ version) did you encounter the bug?
      placeholder: "Example: Android 10"
    validations:
      required: true

  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - Google Play
        - F-Droid
        - Github (Release)
        - Github (Action)
        - Built from Source
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        Please give us a description of what the bug is about.
      placeholder: |
        When I try to set the language to english, the app crashes.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        What did you do for the bug to show up?
        If you can't cause the bug to show up again reliably (and hence don't have a proper set of steps to give us), please still try to give as many details as possible on how you think you encountered the bug.
      placeholder: |
        1. Go to '...'
        2. Press on '....'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Tell us what you expect to happen.
    validations:
      required: true

  - type: textarea
    id: screen-media
    attributes:
      label: Screenshots/Screen recordings
      description: |
        A picture or video is worth a thousand words.
        If applicable, share screenshots or a screen recording to help explain your problem.
      placeholder: |
        <details>
          <summary>Context</summary>
        
          screenshots go in here
        
        </details>

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If you could catch the log of the bug, don't forget to share it. This is the best way to point out any bug.

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Any other information you'd like to include.

  - type: checkboxes
    id: checklist-accept
    attributes:
      label: "Terms and Conditions"
      options:
        - label: "I have read all the rules above and filled in the requiered fields to the best of my ability."
          required: true
        - label: "I accept that if I fail to follow the rules listed above that i will be blocked from interactions with this project."
          required: true
