# Builds the project, signs an API, and then uploads it
name: Android Main Branch CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build, Sign & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN || secrets.GIT_BOT_TOKEN }}
          ref: main

      - name: set up JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/cache@v4.2.4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleDebug
