# Sync repo to the Codeberg mirror
name: Repo sync GitHub -> Codeberg
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://codeberg.org/ottoptj/yamlauncher.git"
          GIT_USERNAME: ottop
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
