name: Validate Gradle Wrapper

on:
  push:
    paths:
      - '**/gradle/wrapper/**'
      - '**/gradlew'
      - '**/gradlew.bat'
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
      - '**/gradlew'
      - '**/gradlew.bat'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.actor == 'dependabot[bot]' && secrets.GITHUB_TOKEN || secrets.GIT_BOT_TOKEN }}
          ref: main

      - name: Validate Gradle Wrapper JAR
        uses: gradle/wrapper-validation-action@v3.5.0
